name: th-format
version: '0.1.1.0'
synopsis: Template Haskell based support for format strings
description: This package implements a Template Haskell quasi quoter for
             format strings.
category: Data
author: Moritz Clasmeier
maintainer: mtesseract@silverratio.net
copyright: 2017-2018 Moritz Clasmeier
license: BSD3
github: mtesseract/th-format
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Data.Format
  ghc-options:
  - -Wall
  dependencies:
  - base >=4.7 && <5
  - Earley >= 0.12.1.0 && < 0.13
  - template-haskell >= 2.12.0.0 && < 2.13
  - text >= 1.2.3.0 && < 1.3
  - haskell-src-meta >= 0.8.0.2 && < 0.9
tests:
  th-format-test:
    main: Tests.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - th-format
    - tasty
    - tasty-hunit
    - text
